### ISSUE TITLE
Work breakdown of Quick Starts Initiative

### ISSUE THREAD

**Issue by jpvajda** [newrelic/nr1-quickstarts#41]
The team will review the quick starts initiative product brief and begin to breakdown the individual feature work so we can organize and estimate and plan the project effectively.

### Acceptance Criteria

- [x] Read the product brief (requirements) ☕ + 📖 
- [x] Work with @jpvajda to break the work down into epics 
- [x] Sequence epics 
- [x] size epics 
- [x] start to construct the basis of a master project plan.

**Comment by jpvajda** [comment]
@zstix for input on the AC 👋
